permalink:  pretty
#relative_permalinks:    true

# Setup
title:  Nauman Shahid
tagline: quaesitor scientiae
email:  naumanshahid@msn.com
description:    "Nauman Shahid"
description2:   "Computer Engineer"
paginate:   2
baseurl:    ''

# Gems
plugins: [jekyll-paginate]